# Generated by Django 5.2 on 2025-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_nick",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите tg chat id",
                max_length=50,
                null=True,
                verbose_name="tg chat id",
            ),
        ),
    ]
