# Generated by Django 5.2 on 2025-04-27 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=200, verbose_name="Название привычки"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "planned_time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите, в какое время планируете выполнять привычку",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "last_execution_time",
                    models.DateField(
                        blank=True,
                        help_text="Укажите время последнего выполнения привычки",
                        null=True,
                        verbose_name="Время последнего выполнения привычки",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите является ли привычка приятной, а не полезной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите периодичность привычки",
                        validators=[
                            django.core.validators.MaxValueValidator(7),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Периодичность привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение за выполнение привычки",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration_time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время, необходимое для выполнения привычки",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, можно ли публиковать привычку в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100,
                        verbose_name="Название места выполнения привычки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Описание места выполнения привычки",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Превью",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
                "ordering": ["title"],
            },
        ),
    ]
