# Generated by Django 5.2 on 2025-04-18 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100,
                        verbose_name="Название места выполнения привычки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Описание места выполнения привычки",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца места",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец места",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200, verbose_name="Действие")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "execution_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Укажите время, когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время, когда необходимо выполнять привычку",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        help_text="Укажите является ли привычка приятной, а не полезной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        default="Ежедневная",
                        help_text="Укажите периодичность привычки",
                        max_length=25,
                        verbose_name="Периодичность привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        help_text="Укажите вознаграждение за выполнение привычки",
                        max_length=200,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Укажите время, необходимое для выполнения привычки",
                        null=True,
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        help_text="Укажите, можно ли публиковать привычку в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца привычки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.place",
                        verbose_name="Место выполнения привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action"],
            },
        ),
    ]
