# Generated by Django 5.2 on 2025-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="execution_time",
        ),
        migrations.AddField(
            model_name="habit",
            name="last_execution_time",
            field=models.DateField(
                blank=True,
                help_text="Укажите время последнего выполнения привычки",
                null=True,
                verbose_name="Время последнего выполнения привычки",
            ),
        ),
    ]
