# Generated by Django 5.2 on 2025-04-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant_habit",
            field=models.BooleanField(
                default=False,
                help_text="Укажите является ли привычка приятной, а не полезной",
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Укажите, можно ли публиковать привычку в общий доступ",
                verbose_name="Признак публичности",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Укажите вознаграждение за выполнение привычки",
                max_length=200,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
