# Generated by Django 5.2 on 2025-04-19 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_is_pleasant_habit_alter_habit_is_public_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца привычки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите место выполнения привычки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits",
                to="habits.place",
                verbose_name="Место выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите связанную привычку",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца места",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец места",
            ),
        ),
    ]
