# Generated by Django 5.2 on 2025-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_remove_habit_execution_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="planned_time",
            field=models.TimeField(
                blank=True,
                help_text="Укажите, в какое время планируете выполнять привычку",
                null=True,
                verbose_name="Время",
            ),
        ),
    ]
