# Generated by Django 5.2 on 2025-04-19 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_owner_alter_habit_place_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца привычки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец привычки",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца места",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец места",
            ),
        ),
    ]
